# AUTHOR : RAVI KUMAR 

# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ravikumar
      POSTGRES_PASSWORD: ravi@123
      POSTGRES_DB: ruby_app

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: ravikumar
      DATABASE_PASSWORD: ravi@123

volumes:
  pgdata:
